# Generated by Django 6.0.2 on 2026-02-19 11:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteAyah',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surah_number', models.IntegerField()),
                ('ayah_number', models.IntegerField()),
                ('number_in_quran', models.IntegerField(default=0)),
                ('surah_name', models.CharField(max_length=100)),
                ('surah_name_arabic', models.CharField(blank=True, max_length=100)),
                ('arabic_text', models.TextField(blank=True)),
                ('translation', models.TextField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
                ('emotion_context', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_ayahs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite_ayahs',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'surah_number', 'ayah_number')},
            },
        ),
    ]
